name: Build solution

on:
  push:
    branches: [ "main", "task-01" ]
  pull_request:
    branches: [ "task-01" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Show compiler version
        run: g++ --version

      - name: Build
        run: |
          mkdir -p build
          g++ -std=c++17 solution.cpp -o build/solution

      - name: Compute artifact name from source branch
        run: |
          REF="${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"
          # Replace slashes with dashes to keep artifact name valid
          REF="${REF//\//-}"
          echo "ARTIFACT_NAME=$REF" >> "$GITHUB_ENV"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: build/solution
          if-no-files-found: error
          retention-days: 7
