name: Build solution

on:
  push:
    branches: [ "task-01" ]
  pull_request:
    branches: [ "task-01" ]

jobs:
  build-checker:
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH_SAFE: ${{ replace(github.event.pull_request.base.ref || github.ref_name, '/', '-') }}
      AUTHOR_SAFE: ${{ replace(github.event.pull_request.user.login || github.actor, '/', '-') }}
    steps:
      - name: Check out base repo main for checker
        uses: actions/checkout@v4
        with:
          # Ensure we fetch the base repository (not the fork) and its main branch
          repository: ${{ github.event.pull_request.base.repo.full_name || github.repository }}
          ref: main
          path: base_main
          fetch-depth: 1

      - name: Build cmp-file checker from base main
        run: |
          mkdir -p base_main/build
          g++ -std=c++17 -O2 -pipe -I base_main \
             base_main/checkers/cmp-file/main.cpp \
             -o base_main/build/cmp-file

      - name: Upload checker artifact
        uses: actions/upload-artifact@v4
        with:
          name: cmp-file-${{ env.AUTHOR_SAFE }}-${{ env.TARGET_BRANCH_SAFE }}
          path: base_main/build/cmp-file
          if-no-files-found: error
          retention-days: 7

  build-solution:
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH_SAFE: ${{ replace(github.event.pull_request.base.ref || github.ref_name, '/', '-') }}
      AUTHOR_SAFE: ${{ replace(github.event.pull_request.user.login || github.actor, '/', '-') }}
    steps:
      - name: Check out repository (PR head)
        uses: actions/checkout@v4

      - name: Show compiler version
        run: g++ --version

      - name: Build solution
        run: |
          mkdir -p build
          g++ -std=c++17 -pipe solution.cpp -o build/solution

      - name: Upload solution artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARGET_BRANCH_SAFE }}-${{ env.AUTHOR_SAFE }}-solution
          path: build/solution
          if-no-files-found: error
          retention-days: 7

  run-examples:
    needs: [ build-checker, build-solution ]
    name: Run solution against example tests
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH_SAFE: ${{ replace(github.event.pull_request.base.ref || github.ref_name, '/', '-') }}
      AUTHOR_SAFE: ${{ replace(github.event.pull_request.user.login || github.actor, '/', '-') }}
    steps:
      - name: Check out PR head (for runner)
        uses: actions/checkout@v4

      - name: Check out target branch tests
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref || github.ref_name }}
          path: base_target
          fetch-depth: 1

      - name: Download checker artifact
        uses: actions/download-artifact@v4
        with:
          name: cmp-file-${{ env.AUTHOR_SAFE }}-${{ env.TARGET_BRANCH_SAFE }}
          path: artifact

      - name: Download solution artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.TARGET_BRANCH_SAFE }}-${{ env.AUTHOR_SAFE }}-solution
          path: artifact

      - name: Make binaries executable
        run: |
          chmod +x artifact/solution
          chmod +x artifact/cmp-file

      - name: Run solution against tests and compare (Python runner)
        run: |
          set -eu
          python3 --version
          python3 run/test_runner.py \
            --solution artifact/solution \
            --checker artifact/cmp-file \
            --tests base_target/tests \
            --out work/out
